version: '2.2'

services:
  app-cidadao:
    image: api-informacoes-cidadao-image:latest
    build:
      context: ./Projetos/api-informacoes-cidadao
    container_name: app-cidadao
    ports:
      - "8080:8080"
  
  db:
    image: postgres:9.5
    container_name: db
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bd-view-safim
    ports:
      - "5432:5432"
  
  app-integracao-safim:
    image: api-integracao-safim:latest
    build:
      context: ./Projetos-Mock/api-integracao-safim
    container_name: app-integracao-safim
    depends_on: 
      - db
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bd-view-safim
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8090:8090"