spring:
  profiles:    active: prod

logging:  pattern:    console: "%d %-5level %logger : %msg%n"
  level:    org.springframework: info

server:  port: 8080
  
# Endpoints para apontar ao serviço do SAFIM
endpoints-safim:
  dev: http://localhost:8090/pessoas/
  prod: http://app-integracao-safim:8090/pessoas/
  
  # Endpoints para apontar ao serviço de Autenticação
endpoints-auth:
  dev: http://localhost:8081/v1/api/valid/
  prod: http://app-auth:8081/v1/api/valid/