spring:
  profiles:    active: development
    
  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bd-cidadao
    username: postgres
    password: postgres
    
  jpa:    hibernate:      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

logging:  pattern:    console: "%d %-5level %logger : %msg%n"
  level:    org.springframework: info
    org.hibernate: debug

server:  port: 8080