spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bd-view-stur
    username: postgres
    password: postgres
  profiles:
    active: prod
    
  jpa:    hibernate:      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  jackson:    date-format: yyyy-MM-dd
    deserialization:      fail-on-unknown-properties: true

logging:  pattern:    console: "%d %-5level %logger : %msg%n"
  level:    org.springframework: info
    
server:  port: 8070
  
  # Endpoints para apontar ao serviço de Autenticação
endpoints-auth:
  dev: http://localhost:8081/v1/api/valid/
  prod: http://app-auth:8081/v1/api/valid/