spring:
  profiles:
    active: development

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info

server:
  port: 8060
  
# Endpoints para apontar ao serviço do SAFIM
endpoints-safim:
  dev: http://localhost:8080/pessoas/
  prod: http://app-cidadao:8080/pessoas/
  
# Endpoints para apontar ao serviço do SAFIM
endpoints-stur:
  dev: http://localhost:8070/imoveis/
  prod: http://app-integracao-stur:8070/imoveis/